version: '3'

services:
    app:
      container_name: address_book_server
      build: .
      ports:
        - 8081:8081
      depends_on:
        - postgres
      networks:
        - fullstack

    postgres:
      image: postgres:latest
      container_name: db_postgres
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST}
      ports:
        - 5432:5432
      networks:
        - fullstack

volumes:
  api:
  database_postgres:

networks:
  fullstack:
    driver: bridge
