---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: go-web-app

spec:
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      initContainers:
      - name: migration
        image: migrate/migrate:latest
        command: ['/migrate']
        args: ['--path', 'internal/database/migrations', '-database', 'postgresql://gorm:gorm12345@10.96.0.3:5432/gorm?sslmode=disable', '-verbose', 'up']

      containers:
      - image: cybernetrunner/address-book:latest
        name: go-web-app
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8081

        env:
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "gorm"
        - name: POSTGRES_USER
          value: "gorm"
        - name: POSTGRES_PASSWORD
          value: "gorm12345"
