---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: cybernetrunner/address-book:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: POSTGRES_PORT
          value: 5432
        - name: POSTGRES_DB
          value: gorm
        - name: POSTGRES_USER
          value: gorm
        - name: POSTGRES_PASSWORD
          value: gorm12345
